name: cottage_booking_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi==0.115.0
      - uvicorn==0.30.6
      - rdflib==7.0.0
      - pydantic==2.9.2
      - python-dateutil==2.9.0.post0
      - jinja2==3.1.4
